 
 /*------------------------------------------------------------------------
    File        : Empty
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : bronco
    Created     : Wed Jul 18 07:57:59 CEST 2018
    Notes       : 
  ----------------------------------------------------------------------*/

using oo.IEmpty.

block-level on error undo, throw.

class oo.Empty implements IEmpty: 

end class.