
/*------------------------------------------------------------------------
    File        : IBase
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : bronco
    Created     : Tue Jul 03 15:35:29 CEST 2018
    Notes       : 
  ----------------------------------------------------------------------*/

using Progress.Lang.*.

interface oo.IBase:  
  
  method public character Identify(name as character).
  
end interface.