
/*------------------------------------------------------------------------
    File        : IDisposable
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : bronco
    Created     : Tue Jun 12 09:19:26 CEST 2018
    Notes       : 
  ----------------------------------------------------------------------*/

using Progress.Lang.*.
using oo.IEmpty.

interface oo.IDisposable inherits IEmpty:  
  
  method public void Dispose().
  
end interface.
